title: The Simon Ensemble
author: The Simon Ensemble
subtitle: 

# for serving locally
# url: http://localhost:4000
url: https://simonensemble.github.io
baseurl: ""

footer_url: "https://simonensemble.github.io"
footer_text: "The Simon Ensemble"

profile-picture: cage_8.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

plugins:
  - jemoji

navbar:
 - name: "people"
   link: "ppl"
 - name: "publications"
   link: "pubs"
 - name: "software"
   link: "software"
 - name: "teaching"
   link: "teaching"
 - name: "join"
   link: "join"
 - name: "blog"
   link: "blog"
