title: The Simon Ensemble
author: The Simon Ensemble
subtitle: 

# for serving locally
# url: http://localhost:4000
url: https://simonensemble.github.io
baseurl: ""

description: "the research website of the Simon Ensemble at Oregon State University"

footer_url: "https://simonensemble.github.io"
footer_text: "The Simon Ensemble"

profile-picture: cage_8.jpg
favicon_location: assets/favicon.ico
title_image: cage_8.jpg
twitter_username: CoryMSimon

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: simonensemble-github-io

plugins:
  - jemoji

navbar:
 - name: "people"
   link: "ppl"
 - name: "publications"
   link: "pubs"
 - name: "software"
   link: "software"
 - name: "teaching"
   link: "teaching"
 - name: "join"
   link: "join"
 - name: "news"
   link: "newz"
 - name: "blog"
   link: "blog"
